#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Warning!: No <path_value>, using default value /usr/share/nginx/html/app.config.js"
    output_file="/usr/share/nginx/html/app.config.js"
else
    output_file="$1"
fi

# Eliminar el archivo si existe
if [ -f "$output_file" ]; then
    rm "$output_file"
fi

echo "Generating $output_file..."

echo "// Autogenerated when service start... " >> "$output_file"
for var in $(printenv | grep "^FRONT"); do
    key=$(echo "$var" | awk -F '=' '{print $1}' | sed 's/^FRONT_//')

    value=$(echo "$var" | awk -F '=' '{print $2}')

    echo "window.${key} = '${value}';" >> "$output_file"
done

echo "Finish $output_file"