services:
  api:
    container_name: ucenin-api
    build:
      context: ./api
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      PGV_USER: "ucenin"
      PGV_PASSWORD: "password" #Match password!
      PGV_HOST: "ucening-pgvector"
      PGV_PORT: 5432
      PGV_DATABASE_NAME: "ucenin"
      EMBEDDING_MODEL: ""
    depends_on:
      - db-vector
    
  db-vector: 
    container_name: ucenin-pgvector
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    #ports:         #Only for dev!
    #  - "5432:5432"
    volumes:
      - db-vector:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "ucenin"
      POSTGRES_PASSWORD: "password" #Change me!
      POSTGRES_DB: "ucenin"
  
  model: 
    container_name: ucenin-ollama
    build: 
      context: ./model
      dockerfile: dockerfile
    restart: unless-stopped
    #ports:           
    #  - "11434:11434"  #Only for dev

volumes:
  db-vector:
    name: ucenin-db-vector