services:
  db-vector:
    container_name: ucenin-pgvector
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    ports: #Only for dev!
      - "${PGV_PORT}:5432"
    volumes:
      - db-vector:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${PGV_USER}"
      POSTGRES_PASSWORD: "${PGV_PASSWORD}"
      POSTGRES_DB: "${PGV_DATABASE_NAME}"

  api:
    container_name: ucenin-api
    build:
      context: ./api
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      - "${API_PORT}:8000"
    environment:
      PGV_USER: "${PGV_USER}"
      PGV_PASSWORD: "${PGV_PASSWORD}"
      PGV_HOST: "ucenin-pgvector"
      PGV_PORT: 5432
      PGV_DATABASE_NAME: "${PGV_DATABASE_NAME}"
      EMBEDDING_MODEL: "${EMBEDDING_MODEL}"
      UCN_MODEL_NAME: "${UCN_MODEL_NAME}"
      OLLAMA_PORT: 11434
      OLLAMA_HOST: "ucening-ollama"
    depends_on:
      - db-vector

  model:
    container_name: ucenin-ollama
    build:
      context: ./model
      dockerfile: dockerfile
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "${OLLAMA_PORT}:11434" #Only for dev

volumes:
  db-vector:
    name: ucenin-db-vector
