version: "3.8"
#ollama
#fastapi
#pgvector
services:
  ollama:
    container_name: ollama
    ports:
      - ${OLLAMA_PORT}:11434
    build:
      context: ./Model
      dockerfile: dockerfile
    volumes:
      - ollama_volume:/root/.ollama #para guardar los modelos creados durante el desarrollo y no sea tan tedioso

  # api:
  # vector_store:

volumes:
  ollama_volume:
